"use client";
import {useEffect,useMemo,useState,type FormEvent} from "react";import AppHeader from "../../../components/app-header";import BabyGrowthChart from "../../../components/baby-growth-chart";
type Growth={id:string;measured_at:string;weight_g:number|null;length_cm:number|null;head_cm:number|null;provider:string;notes:string};type Milestone={id:string;observed_at:string;domain:string;title:string;notes:string;media_url:string;question_for_clinician:boolean};
const domains:Record<string,string>={movement:"Vận động",communication:"Giao tiếp",social:"Xã hội–cảm xúc",cognitive:"Nhận thức",other:"Khác"};
export default function DevelopmentPage(){const[growth,setGrowth]=useState<Growth[]>([]),[milestones,setMilestones]=useState<Milestone[]>([]),[birth,setBirth]=useState<{birthOccurredAt?:string|null;gestationalWeeks?:number|null;babySex?:"male"|"female"|null;premature?:boolean}>({}),[tab,setTab]=useState("growth"),[message,setMessage]=useState("");
 async function load(){const[a,b]=await Promise.all([fetch("/api/baby/development",{cache:"no-store"}),fetch("/api/family/lifecycle",{cache:"no-store"})]);if(a.ok){const x=await a.json();setGrowth(x.growth??[]);setMilestones(x.milestones??[])}if(b.ok)setBirth(await b.json())}useEffect(()=>{void load()},[]);
 const age=useMemo(()=>{if(!birth.birthOccurredAt)return null;const days=Math.max(0,Math.floor((Date.now()-new Date(birth.birthOccurredAt).getTime())/86400000));const early=Math.max(0,40-(birth.gestationalWeeks??40))*7;return{actual:days,corrected:Math.max(0,days-early),useCorrected:early>0&&days<730}},[birth]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),n=(k:string)=>String(f.get(k)??"").trim(),num=(k:string)=>n(k)?Number(n(k)):null;const body=tab==="growth"?{id:crypto.randomUUID(),type:"growth",measuredAt:new Date(n("measuredAt")).toISOString(),weightG:num("weightG"),lengthCm:num("lengthCm"),headCm:num("headCm"),provider:n("provider"),notes:n("notes")}:{id:crypto.randomUUID(),type:"milestone",observedAt:n("observedAt"),domain:n("domain"),title:n("title"),notes:n("notes"),mediaUrl:n("mediaUrl"),questionForClinician:Boolean(f.get("question"))};const r=await fetch("/api/baby/development",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok){e.currentTarget.reset();setMessage("Đã lưu.");await load()}else setMessage("Chưa lưu được. Hãy kiểm tra và thử lại.")}
 return <main className="page development-page"><AppHeader note="Theo dõi để trao đổi với bác sĩ"/><header className="page-intro"><p className="panel-kicker">Lớn lên từng ngày</p><h1>Tăng trưởng & cột mốc</h1>{age?<p>{Math.floor(age.actual/30.44)} tháng tuổi{age.useCorrected?` · tuổi hiệu chỉnh ${Math.floor(age.corrected/30.44)} tháng`:""}</p>:<p>Sẵn sàng sau khi gia đình lưu ngày sinh.</p>}</header>
 <div className="segment-control"><button aria-pressed={tab==="growth"} onClick={()=>setTab("growth")}>Tăng trưởng</button><button aria-pressed={tab==="milestone"} onClick={()=>setTab("milestone")}>Cột mốc</button></div>
 <form className="section medical-form" onSubmit={e=>void save(e)}>{tab==="growth"?<><h2>Thêm lần đo</h2><div className="medical-form-grid"><label>Ngày đo<input name="measuredAt" type="datetime-local" required/></label><label>Cân nặng (g)<input name="weightG" type="number" inputMode="numeric"/></label><label>Chiều dài (cm)<input name="lengthCm" type="number" step=".1" inputMode="decimal"/></label><label>Vòng đầu (cm)<input name="headCm" type="number" step=".1" inputMode="decimal"/></label><label>Nơi đo<input name="provider"/></label></div></>:<><h2>Thêm điều Bé vừa làm được</h2><div className="medical-form-grid"><label>Ngày quan sát<input name="observedAt" type="date" required/></label><label>Nhóm<select name="domain">{Object.entries(domains).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className="medical-wide">Cột mốc<input name="title" required maxLength={160}/></label><label className="medical-wide">Liên kết ảnh/video<input name="mediaUrl" type="url" placeholder="Liên kết kỷ niệm nếu có"/></label></div><label className="check-line"><input name="question" type="checkbox"/> Đưa vào danh sách hỏi bác sĩ</label></>}<label>Ghi chú<textarea name="notes" rows={3}/></label><button className="health-save">Lưu</button><p aria-live="polite">{message}</p></form>
 {tab==="growth"?<><BabyGrowthChart birthOccurredAt={birth.birthOccurredAt??null} babySex={birth.babySex??null} premature={birth.premature} growth={growth}/><section className="section"><h2>Các lần đo</h2><div className="growth-table" role="table">{growth.map(x=><article key={x.id} role="row"><time>{new Intl.DateTimeFormat("vi-VN",{dateStyle:"medium"}).format(new Date(x.measured_at))}</time><span>{x.weight_g?`${(x.weight_g/1000).toFixed(2)} kg`:"—"}</span><span>{x.length_cm?`${x.length_cm} cm`:"—"}</span><span>{x.head_cm?`${x.head_cm} cm vòng đầu`:"—"}</span></article>)}</div></section></>:<section className="section"><h2>Dòng thời gian cột mốc</h2><div className="baby-medical-timeline">{milestones.map(x=><article key={x.id}><small>{domains[x.domain]} · {new Intl.DateTimeFormat("vi-VN").format(new Date(`${x.observed_at}T00:00:00`))}</small><strong>{x.title}</strong>{x.notes?<p>{x.notes}</p>:null}{x.question_for_clinician?<b>Cần hỏi bác sĩ</b>:null}{x.media_url?<a href={x.media_url}>Mở kỷ niệm liên quan</a>:null}</article>)}</div></section>}
 <p className="form-boundary">Cột mốc có khoảng thời gian phát triển khác nhau. Nếu gia đình lo lắng hoặc Bé mất kỹ năng đã có, hãy trao đổi sớm với nhân viên y tế.</p></main>}
