"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import AppHeader from "../../components/app-header";
type Prep={hospitalName:string;hospitalAddress:string;hospitalPhone:string;supportPhone:string;preferences:string;clinicianNotes:string};
type Contraction={id:string;started_at:string;ended_at:string|null};
const empty:Prep={hospitalName:"",hospitalAddress:"",hospitalPhone:"",supportPhone:"",preferences:"",clinicianNotes:""};
export default function BirthPrepPage(){
 const[prep,setPrep]=useState(empty),[events,setEvents]=useState<Contraction[]>([]),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{void Promise.all([fetch("/api/birth-prep",{cache:"no-store"}),fetch("/api/birth-prep/contractions",{cache:"no-store"})]).then(async([a,b])=>{if(a.ok)setPrep(await a.json());if(b.ok)setEvents((await b.json()).events??[])});},[]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 const active=events.find(x=>!x.ended_at);const duration=active?Math.max(0,Math.floor((now-new Date(active.started_at).getTime())/1000)):0;
 const intervals=useMemo(()=>events.filter(x=>x.ended_at).slice(0,6).map((x,i,a)=>({duration:Math.round((new Date(x.ended_at!).getTime()-new Date(x.started_at).getTime())/1000),interval:i<a.length-1?Math.round((new Date(x.started_at).getTime()-new Date(a[i+1].started_at).getTime())/60000):null})),[events]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),v=Object.fromEntries(Object.keys(empty).map(k=>[k,String(f.get(k)??"")]));const r=await fetch("/api/birth-prep",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(v)});if(r.ok)setPrep(await r.json());setBusy(false)}
 async function toggle(){setBusy(true);const id=active?.id??crypto.randomUUID(),time=new Date().toISOString();await fetch("/api/birth-prep/contractions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action:active?"end":"start",time})});setEvents(current=>active?current.map(x=>x.id===id?{...x,ended_at:time}:x):[{id,started_at:time,ended_at:null},...current]);setBusy(false)}
 return <main className="page birth-prep-page"><AppHeader note="Kế hoạch riêng của gia đình"/><header className="page-intro"><p className="panel-kicker">Chuẩn bị ngày gặp Bé</p><h1>Sinh nở, gọn trong một nơi</h1><p>Thông tin cần mở nhanh khi rời nhà hoặc đang theo dõi cơn gò.</p></header>
 <section className="labor-card"><p className="panel-kicker">Chế độ chuyển dạ</p><strong>{active?`${String(Math.floor(duration/60)).padStart(2,"0")}:${String(duration%60).padStart(2,"0")}`:"Sẵn sàng khi cần"}</strong><button type="button" disabled={busy} onClick={()=>void toggle()}>{active?"Kết thúc cơn gò":"Bắt đầu cơn gò"}</button>{intervals.length?<div className="contraction-history">{intervals.map((x,i)=><span key={i}><b>{x.duration} giây</b>{x.interval?` · cách ${x.interval} phút`:""}</span>)}</div>:null}<small>Bộ đếm chỉ giúp ghi lại. Khi có dấu hiệu bất thường hoặc được cơ sở y tế hướng dẫn, hãy gọi nơi khám/cấp cứu.</small></section>
 <div className="birth-contact-actions">{prep.hospitalPhone?<a href={`tel:${prep.hospitalPhone}`}>Gọi nơi sinh</a>:null}{prep.supportPhone?<a href={`tel:${prep.supportPhone}`}>Gọi người hỗ trợ</a>:null}{prep.hospitalAddress?<a href={`https://maps.apple.com/?q=${encodeURIComponent(prep.hospitalAddress)}`} target="_blank" rel="noreferrer">Mở đường đi</a>:null}</div>
 <section className="section"><div className="section-head"><p className="panel-kicker">Thông tin cần mang theo</p><h2>Kế hoạch sinh</h2></div><form className="medical-form" onSubmit={e=>void save(e)}><div className="medical-form-grid"><label>Nơi dự định sinh<input name="hospitalName" defaultValue={prep.hospitalName}/></label><label>Điện thoại nơi sinh<input name="hospitalPhone" inputMode="tel" defaultValue={prep.hospitalPhone}/></label><label className="medical-wide">Địa chỉ<input name="hospitalAddress" defaultValue={prep.hospitalAddress}/></label><label>Người hỗ trợ<input name="supportPhone" inputMode="tel" defaultValue={prep.supportPhone}/></label></div><label>Mong muốn cần trao đổi<textarea name="preferences" rows={4} defaultValue={prep.preferences} placeholder="Người đồng hành, da kề da, nuôi con bằng sữa mẹ… để trao đổi với cơ sở y tế"/></label><label>Dặn dò của bác sĩ<textarea name="clinicianNotes" rows={4} defaultValue={prep.clinicianNotes}/></label><button className="health-save" disabled={busy}>Lưu kế hoạch</button></form></section>
 <nav className="birth-prep-links"><a href="/do-dung">Kiểm tra túi đi sinh</a><a href="/ke-hoach">Việc cần hoàn tất</a><a href="/me-bau#ho-so-kham">Hồ sơ khám thai</a></nav></main>}
