import { verifySessionCookie } from "../../../lib/portal-auth";
import { authorizeMutation } from "../../../lib/photo-upload-server";
function session(r:Request){const c=r.headers.get("cookie")?.split(";").map(x=>x.trim().split("=")).find(([k])=>k==="embe_session")?.slice(1).join("=");return Boolean(process.env.EMBE_PORTAL_SESSION_SECRET&&verifySessionCookie(c,process.env.EMBE_PORTAL_SESSION_SECRET));}
function reply(body:Record<string,unknown>,status:number){return Response.json(body,{status,headers:{"cache-control":"private, no-store"}});}
async function rpc(name:string,body:Record<string,unknown>){const u=process.env.SUPABASE_URL,k=process.env.SUPABASE_SECRET_KEY;if(!u||!k)return null;try{const r=await fetch(`${u.replace(/\/$/,"")}/rest/v1/rpc/${name}`,{method:"POST",cache:"no-store",signal:AbortSignal.timeout(8000),headers:{apikey:k,authorization:`Bearer ${k}`,"content-type":"application/json"},body:JSON.stringify(body)});return r.ok?r.json():null;}catch{return null;}}
const keys=["hospitalName","hospitalAddress","hospitalPhone","supportPhone","preferences","clinicianNotes"] as const;
function normalize(v:unknown){if(!v||typeof v!=="object")return null;const x=v as Record<string,unknown>;const map={hospitalName:x.hospital_name,hospitalAddress:x.hospital_address,hospitalPhone:x.hospital_phone,supportPhone:x.support_phone,preferences:x.preferences,clinicianNotes:x.clinician_notes};return Object.values(map).every(y=>typeof y==="string")?map:null;}
export async function GET(r:Request){if(!session(r))return reply({error:"unauthorized"},401);const x=normalize(await rpc("embe_get_birth_preparation",{}));return x?reply(x,200):reply({error:"temporarily_unavailable"},503);}
export async function PATCH(r:Request){const a=authorizeMutation(r);if(a)return reply({error:a===401?"unauthorized":"forbidden"},a);let v:Record<string,unknown>;try{v=await r.json();}catch{return reply({error:"invalid_request"},400);}if(!v||Object.keys(v).some(k=>!keys.includes(k as typeof keys[number]))||keys.some(k=>typeof v[k]!=="string")||String(v.hospitalName).length>160||String(v.hospitalAddress).length>300||String(v.preferences).length>3000||String(v.clinicianNotes).length>3000||![v.hospitalPhone,v.supportPhone].every(x=>/^[0-9+ ().-]{0,30}$/.test(String(x))))return reply({error:"invalid_request"},400);const x=normalize(await rpc("embe_save_birth_preparation",{p_hospital_name:v.hospitalName,p_hospital_address:v.hospitalAddress,p_hospital_phone:v.hospitalPhone,p_support_phone:v.supportPhone,p_preferences:v.preferences,p_clinician_notes:v.clinicianNotes}));return x?reply(x,200):reply({error:"temporarily_unavailable"},503);}
