-- Intentionally deferred to 20260901144500 so a clean migration replay creates
-- the pregnancy-care tables before extending them. Kept to preserve the
-- migration version already recorded in deployed environments.
