CREATE OR REPLACE FUNCTION public.embe_claim_due_push_notifications(p_now timestamptz,p_limit integer DEFAULT 20) RETURNS jsonb LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $f$
DECLARE result jsonb;
BEGIN
 IF p_now IS NULL OR p_limit NOT BETWEEN 1 AND 50 THEN RAISE EXCEPTION 'invalid push claim';END IF;
 INSERT INTO portal_read_model.push_delivery(subscription_id,notification_key,title,body,target_url)
 SELECT s.id,'daily:'||d.value::text,'EmBe nhắc nhẹ',concat_ws(' · ',CASE WHEN x.tasks_due>0 THEN x.tasks_due||' việc hôm nay' END,CASE WHEN x.pregnancy_due>0 THEN x.pregnancy_due||' lịch khám sắp tới' END,CASE WHEN x.baby_due>0 THEN x.baby_due||' lịch của Bé sắp tới' END,CASE WHEN x.mother_checkin>0 THEN 'Mẹ chưa ghi hồi phục hôm nay' END,CASE WHEN x.inventory_low>0 THEN x.inventory_low||' đồ dùng sắp hết' END),CASE WHEN x.baby_due>0 THEN '/be/ho-so' WHEN x.pregnancy_due>0 THEN '/me-bau#ho-so-kham' WHEN x.mother_checkin>0 THEN '/me' WHEN x.tasks_due>0 THEN '/ke-hoach' ELSE '/do-dung' END
 FROM portal_read_model.push_subscription s CROSS JOIN LATERAL(SELECT(p_now AT TIME ZONE s.timezone)::date value)d CROSS JOIN LATERAL(SELECT
 (SELECT count(*) FROM portal_read_model.family_task t LEFT JOIN portal_read_model.family_task_completion c ON c.task_id=t.id AND c.occurrence_on=d.value WHERE t.deleted_at IS NULL AND c.task_id IS NULL AND t.category<>'appointment' AND t.owner_role IN('family',s.device_role) AND d.value>=t.due_on AND(t.repeat_rule='daily' OR t.repeat_rule='none' AND t.due_on=d.value OR t.repeat_rule='weekly' AND extract(isodow FROM t.due_on)=extract(isodow FROM d.value))) tasks_due,
 (SELECT count(*) FROM portal_read_model.family_task t WHERE t.deleted_at IS NULL AND t.category='appointment' AND t.owner_role IN('family',s.device_role) AND t.due_on BETWEEN d.value AND d.value+1 AND NOT EXISTS(SELECT 1 FROM portal_read_model.family_lifecycle l WHERE l.singleton_id=1 AND l.birth_occurred_at IS NOT NULL)) pregnancy_due,
 (SELECT count(*) FROM portal_read_model.baby_medical_record b WHERE b.deleted_at IS NULL AND b.status='planned' AND (b.occurred_at AT TIME ZONE s.timezone)::date BETWEEN d.value AND d.value+2) baby_due,
 (SELECT CASE WHEN EXISTS(SELECT 1 FROM portal_read_model.family_lifecycle l WHERE l.singleton_id=1 AND l.birth_occurred_at IS NOT NULL AND l.birth_occurred_at>p_now-interval '42 days') AND NOT EXISTS(SELECT 1 FROM portal_read_model.postpartum_health_day h WHERE h.day=d.value) THEN 1 ELSE 0 END) mother_checkin,
 (SELECT count(*) FROM portal_read_model.inventory_item i WHERE i.needs_restock) inventory_low)x
 WHERE s.enabled AND(p_now AT TIME ZONE s.timezone)::time>=s.notify_at AND(p_now AT TIME ZONE s.timezone)::time<s.notify_at+interval '1 hour' AND x.tasks_due+x.pregnancy_due+x.baby_due+x.mother_checkin+x.inventory_low>0 ON CONFLICT(subscription_id,notification_key)DO NOTHING;
 WITH candidates AS(SELECT d.id FROM portal_read_model.push_delivery d WHERE d.attempt_count<5 AND d.next_attempt_at<=p_now AND(d.status IN('pending','failed') OR d.status='processing' AND d.updated_at<p_now-interval '10 minutes')ORDER BY d.created_at LIMIT p_limit FOR UPDATE SKIP LOCKED),claimed AS(UPDATE portal_read_model.push_delivery d SET status='processing',attempt_count=attempt_count+1,updated_at=timezone('utc',now()) FROM candidates WHERE d.id=candidates.id RETURNING d.*) SELECT COALESCE(jsonb_agg(jsonb_build_object('id',c.id,'endpoint',s.endpoint,'p256dh',s.p256dh,'auth',s.auth,'title',c.title,'body',c.body,'url',c.target_url,'tag',c.notification_key)),'[]'::jsonb) INTO result FROM claimed c JOIN portal_read_model.push_subscription s ON s.id=c.subscription_id WHERE s.enabled;RETURN result;
END;$f$;
REVOKE ALL ON FUNCTION public.embe_claim_due_push_notifications(timestamptz,integer) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.embe_claim_due_push_notifications(timestamptz,integer) TO service_role;
