-- Intentionally deferred to 20260901195000 so a clean migration replay creates
-- family_lifecycle before extending it. Kept to preserve the migration version
-- already recorded in deployed environments.
